# Generated by Django 5.2.9 on 2026-01-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=100)),
                ('property_name', models.CharField(max_length=200)),
                ('place_name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('guest_count', models.PositiveIntegerField()),
                ('bedroom_count', models.PositiveIntegerField()),
                ('bathroom_count', models.PositiveIntegerField()),
                ('star_rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('map_location', models.CharField(max_length=255)),
            ],
        ),
    ]
